A.R.G.U.S: AppController Class Reference
AppController Class Reference
Orchestrates runtime modes for ARGUS.
#include <AppController.hpp>
Classes
struct LiveTestOptions
Options used by live test and camera backend check modes.
struct MotionSmokeTestOptions
Options for the motion smoke-test mode.
Public Types
enum class SmokeJoint {
All , Base , Lower , Upper ,
Grip
}
Joint selector used by motion smoke-test mode.
Public Member Functions
AppController () noexcept
Construct the application controller.
~AppController () noexcept
Destroy the application controller.
int runGuardianScenarioDemo ()
Run the scripted guardian scenario demonstration.
int runButtonTest ()
Run physical-button diagnostics.
int runServoCalibration ()
Run interactive raw-pulse servo calibration mode.
int runInteractiveServoConsole ()
Run interactive servo console mode.
int runMotionHomePose ()
Move the arm to the configured home pose and exit.
int runMotionSmokeTest (const MotionSmokeTestOptions &options)
Run motion-only smoke tests using the selected joint scope.
int runCameraBackendCheck (const LiveTestOptions &options)
Run camera backend validation/check mode.
int runLiveMarkerTest (const LiveTestOptions &options)
Run live safety supervision mode.
Detailed Description
Definition at line 18 of file AppController.hpp.
Member Enumeration Documentation
SmokeJoint
enum class AppController::SmokeJoint strong
Enumerator
All
Run the full all-joint smoke sequence.
Base
Run smoke test for base joint only.
Lower
Run smoke test for lower joint only.
Upper
Run smoke test for upper joint only.
Grip
Run smoke test for gripper joint only.
Definition at line 23 of file AppController.hpp.
Constructor & Destructor Documentation
AppController()
AppController::AppController () default noexcept
~AppController()
AppController::~AppController () default noexcept
Member Function Documentation
runButtonTest()
int AppController::runButtonTest ()
Returns
Exit code (0 success, non-zero failure).
Definition at line 2478 of file AppController.cpp.
References PhysicalButtonModule::available(), PhysicalButtonModule::eventToString(), PhysicalButtonModule::lastErrorString(), PhysicalButtonModule::statusString(), and PhysicalButtonModule::waitForEvent().
Referenced by main().
runCameraBackendCheck()
int AppController::runCameraBackendCheck (const LiveTestOptions & options)
Parameters
options Camera/backend options.
Returns
Exit code (0 success, non-zero failure).
Definition at line 3087 of file AppController.cpp.
References AppController::LiveTestOptions::backend_preference, CameraCapture::backendImplementation(), AppController::LiveTestOptions::camera_index, FrameEvent::capture_timestamp, and FrameEvent::image_data.
Referenced by main().
runGuardianScenarioDemo()
int AppController::runGuardianScenarioDemo ()
Returns
Exit code (0 success, non-zero failure).
Definition at line 2420 of file AppController.cpp.
References FRAME_BAD, FRAME_GOOD, GuardianStateMachine::operatorAcknowledge(), GuardianStateMachine::printStatus(), GuardianStateMachine::processFrame(), GuardianStateMachine::setOnClearFreezeCallback(), GuardianStateMachine::setOnFreezeCallback(), and GuardianStateMachine::setOnStateChangeCallback().
Referenced by main().
runInteractiveServoConsole()
int AppController::runInteractiveServoConsole ()
Returns
Exit code (0 success, non-zero failure).
Definition at line 2750 of file AppController.cpp.
References MotionController::enable(), MotionController::initialise(), MotionController::lastErrorString(), MotionController::setTargets(), and MotionController::shutdown().
Referenced by main().
runLiveMarkerTest()
int AppController::runLiveMarkerTest (const LiveTestOptions & options)
Parameters
options Live mode options.
Returns
Exit code (0 success, non-zero failure).
Definition at line 3173 of file AppController.cpp.
References ACK_REQUEST, ALLOW_MOTION, ARM_REQUEST, AppController::LiveTestOptions::auto_ack, PhysicalButtonModule::available(), AppController::LiveTestOptions::backend_preference, CameraCapture::backendImplementation(), MotionChannelMap::base, AppController::LiveTestOptions::camera_index, FrameEvent::capture_timestamp, VisionConfig::depthHueLower1, VisionConfig::depthHueLower2, VisionConfig::depthHueUpper1, VisionConfig::depthHueUpper2, VisionConfig::depthPixelThreshold, VisionConfig::depthSatMax, VisionConfig::depthSatMin, VisionConfig::depthValMax, VisionConfig::depthValMin, DISARM_REQUEST, PhysicalButtonModule::eventToString(), AppController::LiveTestOptions::expected_marker_id, VisionConfig::expectedMarkerId, FAULT, FRAME_BAD, FRAME_GOOD, FREEZE_NOW, FROZEN_UNSAFE, FrameEvent::image_data, MotionController::initialise(), MotionController::lastErrorString(), PhysicalButtonModule::lastErrorString(), VisionProcessor::process(), SafetyResult::processing_time, RESET_PENDING, SAFE, SAFE_MONITORING, MotionController::setTargets(), SafetyResult::state, PhysicalButtonModule::statusString(), SafetyResult::timestamp, UNKNOWN_FAULT, and VisionProcessor::updateConfig().
Referenced by main().
runMotionHomePose()
int AppController::runMotionHomePose ()
Returns
Exit code (0 success, non-zero failure).
Definition at line 2901 of file AppController.cpp.
References MotionController::enable(), MotionController::initialise(), MotionController::lastErrorString(), MotionController::setTargets(), and MotionController::shutdown().
Referenced by main().
runMotionSmokeTest()
int AppController::runMotionSmokeTest (const MotionSmokeTestOptions & options)
Parameters
options Smoke-test options.
Returns
Exit code (0 success, non-zero failure).
Definition at line 2949 of file AppController.cpp.
References MotionChannelMap::base, MotionController::enable(), MotionController::initialise(), AppController::MotionSmokeTestOptions::joint, MotionController::lastErrorString(), MotionController::setTargets(), and MotionController::shutdown().
Referenced by main().
runServoCalibration()
int AppController::runServoCalibration ()
Returns
Exit code (0 success, non-zero failure).
Definition at line 2504 of file AppController.cpp.
References MeArmJointTargets::base_ticks, MotionController::enable(), MeArmJointTargets::gripper_ticks, MotionController::initialise(), MotionController::lastErrorString(), MeArmJointTargets::lower_ticks, MotionController::setTargets(), MotionController::shutdown(), and MeArmJointTargets::upper_ticks.
Referenced by main().
The documentation for this class was generated from the following files:
AppController.hpp
AppController.cpp