A.R.G.U.S: MotionController Class Reference
MotionController Class Reference
Low-level motion output driver for the PCA9685 servo board.
#include <MotionController.hpp>
Public Member Functions
MotionController () noexcept
Construct motion controller in uninitialised state.
~MotionController () noexcept
Destroy motion controller and release resources.
MotionController (const MotionController &)=delete
MotionController & operator= (const MotionController &)=delete
MotionController (MotionController &&)=delete
MotionController & operator= (MotionController &&)=delete
bool initialise (const char *i2c_device_path="/dev/i2c-1", std::uint8_t device_address=0x40, float pwm_frequency_hz=50.0f, MotionChannelMap channel_map={}) noexcept
Initialise PCA9685 output path.
bool setTargets (const MeArmJointTargets &targets) noexcept
Write joint targets to hardware when motion is enabled.
void freeze () noexcept
Freeze/disable motion output immediately.
bool enable () noexcept
Enable motion output after successful initialisation.
void shutdown () noexcept
Disable outputs and close hardware resources.
bool isInitialised () const noexcept
Check whether controller was successfully initialised.
bool isEnabled () const noexcept
Check whether motion output is currently enabled.
bool isFrozen () const noexcept
Check whether output is currently frozen.
MotionOutputState outputState () const noexcept
Get current output state.
MotionControllerError lastError () const noexcept
Get last controller error code.
const char * lastErrorString () const noexcept
Get human-readable last error string.
Static Public Attributes
static constexpr std::uint8_t kServoCount = 4
Number of logical servos controlled.
static constexpr std::uint8_t kPca9685ChannelCount = 16
PCA9685 total channels.
static constexpr std::uint16_t kMaxPulseTicks = 4095
Maximum 12-bit pulse value.
Detailed Description
Definition at line 55 of file MotionController.hpp.
Constructor & Destructor Documentation
MotionController() [1/3]
MotionController::MotionController () noexcept
Definition at line 68 of file MotionController.cpp.
~MotionController()
MotionController::~MotionController () noexcept
Definition at line 76 of file MotionController.cpp.
References shutdown().
MotionController() [2/3]
MotionController::MotionController (const MotionController &) delete
MotionController() [3/3]
MotionController::MotionController (MotionController &&) delete
Member Function Documentation
enable()
bool MotionController::enable () noexcept
Returns
true when enable succeeds, otherwise false.
Definition at line 190 of file MotionController.cpp.
References DEVICE_IO_FAILED, ENABLED, FAULT, NONE, NOT_INITIALISED, and UNINITIALISED.
Referenced by AppController::runInteractiveServoConsole(), AppController::runMotionHomePose(), AppController::runMotionSmokeTest(), and AppController::runServoCalibration().
freeze()
void MotionController::freeze () noexcept
Definition at line 172 of file MotionController.cpp.
References DEVICE_IO_FAILED, DISABLED, FAULT, and NONE.
initialise()
bool MotionController::initialise (const char * i2c_device_path = "/dev/i2c-1", std::uint8_t device_address = 0x40, float pwm_frequency_hz = 50.0f, MotionChannelMap channel_map = {}) noexcept
Parameters
i2c_device_path I2C device path (for example /dev/i2c-1).
device_address I2C slave address of the PCA9685.
pwm_frequency_hz PWM frequency in Hz.
channel_map Logical joint-to-channel mapping.
Returns
true on success, otherwise false and lastError() set.
Definition at line 80 of file MotionController.cpp.
References DEVICE_IO_FAILED, DEVICE_OPEN_FAILED, DEVICE_SELECT_FAILED, DISABLED, FAULT, INVALID_ARGUMENT, and NONE.
Referenced by AppController::runInteractiveServoConsole(), AppController::runLiveMarkerTest(), AppController::runMotionHomePose(), AppController::runMotionSmokeTest(), and AppController::runServoCalibration().
isEnabled()
bool MotionController::isEnabled () const noexcept
Returns
true if enabled, otherwise false.
Definition at line 229 of file MotionController.cpp.
References ENABLED.
isFrozen()
bool MotionController::isFrozen () const noexcept
Returns
true if frozen, otherwise false.
Definition at line 233 of file MotionController.cpp.
isInitialised()
bool MotionController::isInitialised () const noexcept
Returns
true if initialised, otherwise false.
Definition at line 224 of file MotionController.cpp.
References FAULT, and UNINITIALISED.
lastError()
MotionControllerError MotionController::lastError () const noexcept
Returns
Error code.
Definition at line 241 of file MotionController.cpp.
lastErrorString()
const char * MotionController::lastErrorString () const noexcept
Returns
Null-terminated string describing last error.
Definition at line 245 of file MotionController.cpp.
References DEVICE_IO_FAILED, DEVICE_OPEN_FAILED, DEVICE_SELECT_FAILED, INVALID_ARGUMENT, NONE, and NOT_INITIALISED.
Referenced by AppController::runInteractiveServoConsole(), AppController::runLiveMarkerTest(), AppController::runMotionHomePose(), AppController::runMotionSmokeTest(), and AppController::runServoCalibration().
operator=() [1/2]
MotionController & MotionController::operator= (const MotionController &) delete
operator=() [2/2]
MotionController & MotionController::operator= (MotionController &&) delete
outputState()
MotionOutputState MotionController::outputState () const noexcept
Returns
Output state enum.
Definition at line 237 of file MotionController.cpp.
setTargets()
bool MotionController::setTargets (const MeArmJointTargets & targets) noexcept
Parameters
targets Joint pulse-tick targets.
Returns
true on success, otherwise false.
Definition at line 138 of file MotionController.cpp.
References DEVICE_IO_FAILED, ENABLED, FAULT, INVALID_ARGUMENT, NONE, NOT_INITIALISED, and UNINITIALISED.
Referenced by AppController::runInteractiveServoConsole(), AppController::runLiveMarkerTest(), AppController::runMotionHomePose(), AppController::runMotionSmokeTest(), and AppController::runServoCalibration().
shutdown()
void MotionController::shutdown () noexcept
Definition at line 211 of file MotionController.cpp.
References NONE, and UNINITIALISED.
Referenced by AppController::runInteractiveServoConsole(), AppController::runMotionHomePose(), AppController::runMotionSmokeTest(), AppController::runServoCalibration(), and ~MotionController().
Member Data Documentation
kMaxPulseTicks
constexpr std::uint16_t MotionController::kMaxPulseTicks = 4095 static constexpr
Definition at line 59 of file MotionController.hpp.
kPca9685ChannelCount
constexpr std::uint8_t MotionController::kPca9685ChannelCount = 16 static constexpr
Definition at line 58 of file MotionController.hpp.
kServoCount
constexpr std::uint8_t MotionController::kServoCount = 4 static constexpr
Definition at line 57 of file MotionController.hpp.
The documentation for this class was generated from the following files:
MotionController.hpp
MotionController.cpp